
-- Create a table to track events for rate limiting.
CREATE TABLE public.rate_limit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    action TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Add an index for faster lookups.
CREATE INDEX idx_rate_limit_events_user_action_time ON public.rate_limit_events (user_id, action, created_at DESC);

-- Enable Row Level Security
ALTER TABLE public.rate_limit_events ENABLE ROW LEVEL SECURITY;

-- Policies for rate_limit_events:
-- Deny all access to users from the client-side. This table should only be accessible
-- by backend functions running with the service_role key, which bypasses RLS.
CREATE POLICY "Deny all access"
ON public.rate_limit_events
FOR ALL
USING (false)
WITH CHECK (false);
